#!/bin/bash


#=================================================
# GENERIC STARTING
#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source _common.sh
source /usr/share/yunohost/helpers

ynh_abort_if_errors

#=================================================
# RETRIEVE ARGUMENTS
#=================================================

final_path=$(ynh_app_setting_get $app final_path)

#=================================================
# CUSTOM SETTERS
#=================================================

set__admin_route () {
    ynh_permission_url --permission="admin" --url="$admin_route"
    ynh_update_config_var --file="$final_path/.env" --key=admin_route --value="$admin_route"
    ynh_app_setting_set --app=$app --key=admin_route --value="$admin_route"
}

set__client_max_body_size () {
    ynh_update_config_var --file="/etc/nginx/conf.d/$domain.d/$app.conf" --key=client_max_body_size --value="$client_max_body_size"
    ynh_app_setting_set --app=$app --key=client_max_body_size --value="$client_max_body_size"
}

#=================================================
# GENERIC FINALIZATION
#=================================================
ynh_app_config_run $1
